name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (workspaces)
        run: npm ci

      - name: Build server
        run: npm --prefix server run build
